"""
showChar Ren'Py Statement Generator

Generates two .rpy files per character folder that together provide a
'showChar' custom statement for scenario writers:

    showChar Niya happy at center with dissolve

Instead of the classic:

    show niya a_2 at center with dissolve

Files generated:
  00showchar.rpy      - Shared infrastructure (statement registration, prefix detection)
  showchar_<Name>.rpy - Per-character emotion and outfit mappings
"""

from pathlib import Path
from typing import Dict, List, Optional, Tuple

from ..logging_utils import log_info, log_warning


# ═══════════════════════════════════════════════════════════════════════════════
# EMOTION NAME MAPPINGS
# ═══════════════════════════════════════════════════════════════════════════════

# Canonical emotion name for each expression index (matches EXPRESSIONS_SEQUENCE order)
EMOTION_NAMES: List[str] = [
    "neutral",      # 0
    "talking",      # 1
    "happy",        # 2
    "sad",          # 3
    "angry",        # 4
    "surprised",    # 5
    "embarrassed",  # 6
    "confused",     # 7
    "laughing",     # 8
    "scared",       # 9
    "crying",       # 10
    "skeptical",    # 11
    "pensive",      # 12
    "confident",    # 13
    "playful",      # 14
    "sleepy",       # 15
    "aroused",      # 16
]

# Aliases map to canonical names (only included if the canonical emotion exists)
EMOTION_ALIASES: Dict[str, str] = {
    "annoyed": "angry",
    "shock": "surprised",
    "embarrass": "embarrassed",
    "laugh": "laughing",
    "terrified": "scared",
    "doubtful": "skeptical",
    "thinking": "pensive",
    "smug": "confident",
    "wink": "playful",
    "tired": "sleepy",
    "horny": "aroused",
}


# ═══════════════════════════════════════════════════════════════════════════════
# INFRASTRUCTURE TEMPLATE (00showchar.rpy)
# ═══════════════════════════════════════════════════════════════════════════════

_INFRASTRUCTURE_TEMPLATE = r'''# showChar - Friendly expression commands for AI-generated ST characters
# Generated by ST Sprite Creator. Do not edit.
#
# Usage:
#   showChar <name> <emotion> [at <transform>, ...] [with <transition>]
#
# Examples:
#   showChar Niya happy at center with dissolve
#   showChar Niya sad at left
#   showChar Niya surprised

init python early:

    # Global registries populated by per-character showchar_<name>.rpy files
    if not hasattr(renpy.store, "_showchar_emotions"):
        renpy.store._showchar_emotions = {}
    if not hasattr(renpy.store, "_showchar_outfits"):
        renpy.store._showchar_outfits = {}

    # Cache: maps lowercase name -> actual code_name on the store
    _showchar_name_cache = {}
    _showchar_prefix_cache = [None]  # None=not looked up, ""=no prefix

    def _showchar_detect_prefix():
        """Detect the current scenario's prefix from the executing script's path."""
        if _showchar_prefix_cache[0] is not None:
            return _showchar_prefix_cache[0] if _showchar_prefix_cache[0] else None

        try:
            current_fn, _line = renpy.get_filename_line()
            if current_fn:
                fn = str(current_fn).replace("\\", "/")
                # Extract scenario folder name from path like:
                # "game/scenario/Testing_Emotions/story/template.rpy"
                # or "scenario/Testing_Emotions/story/template.rpy"
                parts = fn.split("/")
                for i, part in enumerate(parts):
                    if part == "scenario" and i + 1 < len(parts):
                        scenario_folder = parts[i + 1]
                        # Read scenario.yml to get prefix
                        yml_path = "scenario/{}/scenario.yml".format(scenario_folder)
                        try:
                            f = renpy.file(yml_path)
                            try:
                                raw = f.read()
                            finally:
                                f.close()
                            if isinstance(raw, bytes):
                                text = raw.decode("utf-8", "ignore")
                            else:
                                text = str(raw)
                            for line in text.splitlines():
                                stripped = line.strip()
                                if stripped.lower().startswith("prefix:"):
                                    value = stripped.split(":", 1)[1].strip().strip("'\"")
                                    if value:
                                        _showchar_prefix_cache[0] = value
                                        return value
                        except Exception:
                            pass
                        break
        except Exception:
            pass

        _showchar_prefix_cache[0] = ""
        return None

    def _showchar_resolve_person(name):
        """Find the Person object for a character name (case-insensitive, prefix-aware).

        Searches the ST characters dict for a matching character. Prefers
        the current scenario's character when the same name exists in
        multiple scenarios (e.g. 'temo_Niya' over 'ynb_Niya').
        """
        # Check cache first
        if name in _showchar_name_cache:
            cached = _showchar_name_cache[name]
            person = getattr(renpy.store, cached, None)
            if person is not None:
                return person, cached

        characters = getattr(renpy.store, "characters", {})
        name_lower = name.lower()
        suffix = "_{}".format(name_lower)

        # Detect the current scenario's prefix
        prefix = _showchar_detect_prefix()

        # If we know the prefix, try the exact prefixed name first
        if prefix:
            target = "{}_{}".format(prefix, name_lower)
            for cname in characters:
                if cname.lower() == target:
                    person = getattr(renpy.store, cname, None)
                    if person is not None:
                        _showchar_name_cache[name] = cname
                        return person, cname

        # Fallback: any prefixed match
        for cname in characters:
            cname_lower = cname.lower()
            if cname_lower.endswith(suffix):
                person = getattr(renpy.store, cname, None)
                if person is not None:
                    _showchar_name_cache[name] = cname
                    return person, cname

        # Fallback: exact name match (base game characters)
        for cname in characters:
            if cname.lower() == name_lower:
                person = getattr(renpy.store, cname, None)
                if person is not None:
                    _showchar_name_cache[name] = cname
                    return person, cname

        return None, None

    # Track last shown emotion per character for "keep current" support
    _showchar_last_emotion = {}

    def _showchar_parse(lexer):
        """Parse: showChar <name> [<emotion>] [at <transform>, ...] [with <transition>]
        If emotion is omitted, the character keeps their current expression."""
        name = lexer.word()
        if not name:
            lexer.error("showChar requires a character name.")
            return {"name": "", "emotion": None, "at_names": [], "with_name": None}

        # Read the next word - could be emotion, 'at', or 'with'
        emotion = None
        at_names = []
        with_name = None
        got_at = False
        got_with = False

        if not lexer.eol():
            # Try keywords first (they only consume if matched)
            if lexer.keyword("at"):
                got_at = True
            elif lexer.keyword("with"):
                got_with = True
            else:
                emotion = lexer.word()

        # Handle 'at' if we already consumed it
        if got_at:
            tname = lexer.word()
            if tname:
                at_names.append(tname)
            while lexer.match(","):
                tname = lexer.word()
                if tname:
                    at_names.append(tname)

        # Handle 'with' if we already consumed it
        if got_with:
            with_name = lexer.word()

        # Continue parsing remaining 'at' and 'with' clauses
        while not lexer.eol():
            if lexer.keyword("at"):
                tname = lexer.word()
                if not tname:
                    lexer.error("Expected transform name after 'at'.")
                    break
                at_names.append(tname)
                while lexer.match(","):
                    tname = lexer.word()
                    if tname:
                        at_names.append(tname)
            elif lexer.keyword("with"):
                with_name = lexer.word()
                if not with_name:
                    lexer.error("Expected transition name after 'with'.")
                    break
            else:
                lexer.error("showChar: unexpected token. Syntax: showChar <name> [emotion] [at ...] [with ...]")
                lexer.rest()
                break

        lexer.expect_noblock("showChar")
        lexer.expect_eol()

        return {
            "name": name.lower(),
            "emotion": emotion.lower() if emotion else None,
            "at_names": at_names,
            "with_name": with_name,
        }

    def _showchar_execute(parsed):
        """Execute a showChar statement by resolving emotion + outfit to a show command."""
        name = parsed["name"]
        emotion = parsed["emotion"]

        emotions = getattr(renpy.store, "_showchar_emotions", {})
        outfits = getattr(renpy.store, "_showchar_outfits", {})

        char_emotions = emotions.get(name)
        if char_emotions is None:
            renpy.notify("showChar: no emotion data for '{}'.".format(name))
            return

        # If no emotion specified, reuse the last one (or default to neutral)
        if emotion is None:
            emotion = _showchar_last_emotion.get(name, "neutral")

        idx = char_emotions.get(emotion)
        if idx is None:
            renpy.notify("showChar: unknown emotion '{}' for '{}'.".format(emotion, name))
            return

        # Remember this emotion for next time
        _showchar_last_emotion[name] = emotion

        # Resolve the person object (handles prefix and case automatically)
        person, code_name = _showchar_resolve_person(name)
        if person is None:
            renpy.notify("showChar: character '{}' not found.".format(name))
            return

        # Get current outfit and map to pose letter
        current_outfit = getattr(person, "outfit", "")
        char_outfits = outfits.get(name, {})
        outfit_key = current_outfit.lower() if current_outfit else ""
        pose_letter = char_outfits.get(outfit_key, "a")

        # Build the expression string
        expr = "{}_{}".format(pose_letter, idx)

        # Resolve transforms
        at_list = []
        for tname in parsed["at_names"]:
            obj = getattr(renpy.store, tname, None)
            if obj is not None:
                at_list.append(obj)

        # Show the character (simple string call, same as native show statement)
        renpy.show("{} {}".format(code_name, expr), at_list=at_list)

        # Apply transition
        if parsed["with_name"]:
            trans = getattr(renpy.store, parsed["with_name"], None)
            if trans is not None:
                renpy.transition(trans)

    def _showchar_lint(parsed):
        """Lint: validate emotion name at compile time."""
        emotions = getattr(renpy.store, "_showchar_emotions", {})
        char_emotions = emotions.get(parsed["name"])
        if char_emotions is not None and parsed["emotion"] not in char_emotions:
            renpy.error("showChar: unknown emotion '{}' for '{}'.".format(
                parsed["emotion"], parsed["name"]))

    # Register the statement (guarded for when multiple characters each have a copy)
    try:
        renpy.register_statement(
            "showChar",
            parse=_showchar_parse,
            execute=_showchar_execute,
            lint=_showchar_lint,
        )
    except Exception:
        pass
'''


# ═══════════════════════════════════════════════════════════════════════════════
# DATA TEMPLATE (showchar_<Name>.rpy)
# ═══════════════════════════════════════════════════════════════════════════════

_DATA_TEMPLATE = '''# showChar data for {display_name}
# Generated by ST Sprite Creator. Do not edit.
#
# Provides emotion and outfit mappings for the showChar command.
# Usage: showChar {char_name} <emotion> [at <transform>] [with <transition>]

init python:
    _showchar_emotions["{name_lower}"] = {{
{emotion_entries}
    }}

    _showchar_outfits["{name_lower}"] = {{
{outfit_entries}
    }}
'''


# ═══════════════════════════════════════════════════════════════════════════════
# GENERATOR FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def _scan_character_outfits(char_dir: Path) -> Dict[str, str]:
    """Scan character folder to build outfit_name -> pose_letter mapping."""
    outfit_map: Dict[str, str] = {}

    for item in sorted(char_dir.iterdir()):
        if item.is_dir() and len(item.name) == 1 and item.name.isalpha():
            pose_letter = item.name
            outfits_dir = item / "outfits"
            if outfits_dir.exists():
                for outfit_file in outfits_dir.iterdir():
                    if outfit_file.suffix.lower() in ('.png', '.jpg', '.jpeg', '.webp'):
                        outfit_name = outfit_file.stem
                        outfit_map[outfit_name.lower()] = pose_letter

    return outfit_map


def _count_expressions(char_dir: Path) -> int:
    """Count how many expressions exist in the first pose's faces/face/ dir."""
    for item in sorted(char_dir.iterdir()):
        if item.is_dir() and len(item.name) == 1 and item.name.isalpha():
            face_dir = item / "faces" / "face"
            if face_dir.exists():
                count = 0
                for f in face_dir.iterdir():
                    if f.suffix.lower() in ('.png', '.jpg', '.jpeg', '.webp'):
                        try:
                            int(f.stem)
                            count += 1
                        except ValueError:
                            pass
                return count
    return 0


def generate_showchar_infrastructure(char_dir: Path) -> None:
    """Write 00showchar.rpy if it doesn't already exist."""
    filepath = char_dir / "00showchar.rpy"
    if filepath.exists():
        log_info(f"showChar infrastructure already exists: {filepath}")
        return

    filepath.write_text(_INFRASTRUCTURE_TEMPLATE, encoding="utf-8")
    log_info(f"Generated showChar infrastructure: {filepath}")


def generate_showchar_data(char_dir: Path) -> None:
    """Generate the per-character showchar_<Name>.rpy data file."""
    char_name = char_dir.name
    name_lower = char_name.lower()

    # Scan outfits
    outfit_map = _scan_character_outfits(char_dir)
    if not outfit_map:
        log_warning(f"showChar: no outfits found for {char_name}, skipping data file")
        return

    # Count expressions
    expr_count = _count_expressions(char_dir)
    if expr_count == 0:
        log_warning(f"showChar: no expressions found for {char_name}, skipping data file")
        return

    # Build emotion map (only include emotions that exist)
    emotion_lines = []
    available_emotions = set()
    for i in range(min(expr_count, len(EMOTION_NAMES))):
        ename = EMOTION_NAMES[i]
        emotion_lines.append(f'        "{ename}": "{i}",')
        available_emotions.add(ename)

    # Add aliases for available emotions
    alias_lines = []
    for alias, canonical in sorted(EMOTION_ALIASES.items()):
        if canonical in available_emotions:
            # Find the index of the canonical emotion
            idx = EMOTION_NAMES.index(canonical)
            alias_lines.append(f'        "{alias}": "{idx}",')

    if alias_lines:
        emotion_lines.append("        # Aliases")
        emotion_lines.extend(alias_lines)

    # Build outfit entries
    outfit_lines = []
    for outfit_name, pose_letter in sorted(outfit_map.items()):
        outfit_lines.append(f'        "{outfit_name}": "{pose_letter}",')

    # Write the data file
    content = _DATA_TEMPLATE.format(
        display_name=char_name,
        char_name=char_name,
        name_lower=name_lower,
        emotion_entries="\n".join(emotion_lines),
        outfit_entries="\n".join(outfit_lines),
    )

    filepath = char_dir / f"showchar_{char_name}.rpy"
    filepath.write_text(content, encoding="utf-8")
    log_info(f"Generated showChar data: {filepath}")


def generate_showchar_files(char_dir: Path) -> None:
    """
    Generate showChar .rpy files for a character folder.

    Creates:
      - 00showchar.rpy (shared infrastructure, skipped if exists)
      - showchar_<Name>.rpy (per-character data, always regenerated)
    """
    generate_showchar_infrastructure(char_dir)
    generate_showchar_data(char_dir)
